SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3 # 1: Small, 2: Medium, 3: Large
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_SPAWN_COUNT_MULTIPLIER = 15
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_ACCELERATION = 300
PLAYER_DRAG = 0.9

SHOT_RADIUS = 5
SHOT_SPEED = 500
SHOT_RATE = 0.4 # seconds

POWERUP_TIME_SHIELD = 3.0 # seconds
POWERUP_TIME_SHOT = 5.0 # seconds

MAX_BONUS = 420

COLOR_SHOT = "#FF2E63"
COLOR_PLAYER = "#9929EA"
COLOR_SHIELD = "#08D9D6"
COLOR_UI = "#333333"
COLOR_ASTEROID = "#FFFFFF"